# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
sudo: required

install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# /usr/bin/clang is 3.4, lets override with modern one.
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.7
    - valgrind
    - debhelper
    - scons
    - protobuf-compiler
    - libdbus-1-dev
    - libdbus-c++-dev
    - libprotobuf-dev
    - libsnappy-dev
    - libleveldb-dev
    - libglib2.0-dev
    - libctemplate-dev
    - libssl-dev
    - libtspi-dev
    - libpam0g-dev
    - fakeroot
    - build-essential
    - trousers
os:
  - linux
  - osx
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
script:
  - ./travis.sh
notifications:
  email: false
sudo: false
